# -*- coding: utf-8 -*-
"""cropapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uo4oc3--KEDNBww_xMUxfD1CT36OIn03
"""

import streamlit as st
import numpy as np
import joblib
from tensorflow.keras.models import load_model

def load_all():
    model = load_model("crop_rnn_model.h5")
    scaler = joblib.load("scaler.pkl")
    label_encoder = joblib.load("label_encoder.pkl")
    return model, scaler, label_encoder

model, scaler, label_encoder = load_all()

st.title("🌾 AI Crop Recommendation (RNN + Streamlit)")
st.write("Enter soil and climate parameters to get a crop recommendation.")

moisture = st.number_input("Soil_Moisture ", min_value=0.0, max_value=200.0, value=50.0)
temperature = st.number_input("Temperature (°C)", min_value=-10.0, max_value=60.0, value=25.0)
humidity = st.number_input("Humidity (%)", min_value=0.0, max_value=100.0, value=60.0)
ph = st.number_input("Soil_pH", min_value=0.0, max_value=14.0, value=6.5)
rainfall = st.number_input("Rainfall (mm)", min_value=0.0, max_value=500.0, value=100.0)

if st.button("Recommend Crop"):
    # 3. Input ko numpy array me lo
    features = np.array([[moisture, temperature, humidity, ph, rainfall]])

    # 4. Scale
    features_scaled = scaler.transform(features)

    # 5. RNN ke liye reshape: (samples, timesteps, features)
    features_scaled = features_scaled.reshape((features_scaled.shape[0], 1, features_scaled.shape[1]))

    # 6. Predict
    probs = model.predict(features_scaled)
    class_index = np.argmax(probs, axis=1)[0]
    crop_name = label_encoder.inverse_transform([class_index])[0]

    st.success(f"🌱 Recommended Crop: **{crop_name}**")